/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from 'iglooroom';

import { defineCustomElements } from 'iglooroom/loader';

defineCustomElements();
export const IrAccomodations = /*@__PURE__*/createReactComponent<JSX.IrAccomodations, HTMLIrAccomodationsElement>('ir-accomodations');
export const IrAdultChildCounter = /*@__PURE__*/createReactComponent<JSX.IrAdultChildCounter, HTMLIrAdultChildCounterElement>('ir-adult-child-counter');
export const IrAlertDialog = /*@__PURE__*/createReactComponent<JSX.IrAlertDialog, HTMLIrAlertDialogElement>('ir-alert-dialog');
export const IrAuth = /*@__PURE__*/createReactComponent<JSX.IrAuth, HTMLIrAuthElement>('ir-auth');
export const IrAvailibilityHeader = /*@__PURE__*/createReactComponent<JSX.IrAvailibilityHeader, HTMLIrAvailibilityHeaderElement>('ir-availibility-header');
export const IrBadge = /*@__PURE__*/createReactComponent<JSX.IrBadge, HTMLIrBadgeElement>('ir-badge');
export const IrBadgeGroup = /*@__PURE__*/createReactComponent<JSX.IrBadgeGroup, HTMLIrBadgeGroupElement>('ir-badge-group');
export const IrBanner = /*@__PURE__*/createReactComponent<JSX.IrBanner, HTMLIrBannerElement>('ir-banner');
export const IrBookingCode = /*@__PURE__*/createReactComponent<JSX.IrBookingCode, HTMLIrBookingCodeElement>('ir-booking-code');
export const IrBookingDetails = /*@__PURE__*/createReactComponent<JSX.IrBookingDetails, HTMLIrBookingDetailsElement>('ir-booking-details');
export const IrBookingEngine = /*@__PURE__*/createReactComponent<JSX.IrBookingEngine, HTMLIrBookingEngineElement>('ir-booking-engine');
export const IrBookingListing = /*@__PURE__*/createReactComponent<JSX.IrBookingListing, HTMLIrBookingListingElement>('ir-booking-listing');
export const IrBookingPage = /*@__PURE__*/createReactComponent<JSX.IrBookingPage, HTMLIrBookingPageElement>('ir-booking-page');
export const IrBookingSummary = /*@__PURE__*/createReactComponent<JSX.IrBookingSummary, HTMLIrBookingSummaryElement>('ir-booking-summary');
export const IrBookingWidget = /*@__PURE__*/createReactComponent<JSX.IrBookingWidget, HTMLIrBookingWidgetElement>('ir-booking-widget');
export const IrButton = /*@__PURE__*/createReactComponent<JSX.IrButton, HTMLIrButtonElement>('ir-button');
export const IrCalendar = /*@__PURE__*/createReactComponent<JSX.IrCalendar, HTMLIrCalendarElement>('ir-calendar');
export const IrCarousel = /*@__PURE__*/createReactComponent<JSX.IrCarousel, HTMLIrCarouselElement>('ir-carousel');
export const IrCheckbox = /*@__PURE__*/createReactComponent<JSX.IrCheckbox, HTMLIrCheckboxElement>('ir-checkbox');
export const IrCheckoutPage = /*@__PURE__*/createReactComponent<JSX.IrCheckoutPage, HTMLIrCheckoutPageElement>('ir-checkout-page');
export const IrCheckoutSkeleton = /*@__PURE__*/createReactComponent<JSX.IrCheckoutSkeleton, HTMLIrCheckoutSkeletonElement>('ir-checkout-skeleton');
export const IrCouponDialog = /*@__PURE__*/createReactComponent<JSX.IrCouponDialog, HTMLIrCouponDialogElement>('ir-coupon-dialog');
export const IrCreditCardInput = /*@__PURE__*/createReactComponent<JSX.IrCreditCardInput, HTMLIrCreditCardInputElement>('ir-credit-card-input');
export const IrDatePopup = /*@__PURE__*/createReactComponent<JSX.IrDatePopup, HTMLIrDatePopupElement>('ir-date-popup');
export const IrDateRange = /*@__PURE__*/createReactComponent<JSX.IrDateRange, HTMLIrDateRangeElement>('ir-date-range');
export const IrDialog = /*@__PURE__*/createReactComponent<JSX.IrDialog, HTMLIrDialogElement>('ir-dialog');
export const IrDrawer = /*@__PURE__*/createReactComponent<JSX.IrDrawer, HTMLIrDrawerElement>('ir-drawer');
export const IrFacilities = /*@__PURE__*/createReactComponent<JSX.IrFacilities, HTMLIrFacilitiesElement>('ir-facilities');
export const IrFooter = /*@__PURE__*/createReactComponent<JSX.IrFooter, HTMLIrFooterElement>('ir-footer');
export const IrGallery = /*@__PURE__*/createReactComponent<JSX.IrGallery, HTMLIrGalleryElement>('ir-gallery');
export const IrGoogleMaps = /*@__PURE__*/createReactComponent<JSX.IrGoogleMaps, HTMLIrGoogleMapsElement>('ir-google-maps');
export const IrGuestCounter = /*@__PURE__*/createReactComponent<JSX.IrGuestCounter, HTMLIrGuestCounterElement>('ir-guest-counter');
export const IrIcons = /*@__PURE__*/createReactComponent<JSX.IrIcons, HTMLIrIconsElement>('ir-icons');
export const IrInput = /*@__PURE__*/createReactComponent<JSX.IrInput, HTMLIrInputElement>('ir-input');
export const IrInterceptor = /*@__PURE__*/createReactComponent<JSX.IrInterceptor, HTMLIrInterceptorElement>('ir-interceptor');
export const IrInvoice = /*@__PURE__*/createReactComponent<JSX.IrInvoice, HTMLIrInvoiceElement>('ir-invoice');
export const IrLanguagePicker = /*@__PURE__*/createReactComponent<JSX.IrLanguagePicker, HTMLIrLanguagePickerElement>('ir-language-picker');
export const IrLoyalty = /*@__PURE__*/createReactComponent<JSX.IrLoyalty, HTMLIrLoyaltyElement>('ir-loyalty');
export const IrMenu = /*@__PURE__*/createReactComponent<JSX.IrMenu, HTMLIrMenuElement>('ir-menu');
export const IrModal = /*@__PURE__*/createReactComponent<JSX.IrModal, HTMLIrModalElement>('ir-modal');
export const IrNav = /*@__PURE__*/createReactComponent<JSX.IrNav, HTMLIrNavElement>('ir-nav');
export const IrPagination = /*@__PURE__*/createReactComponent<JSX.IrPagination, HTMLIrPaginationElement>('ir-pagination');
export const IrPaymentView = /*@__PURE__*/createReactComponent<JSX.IrPaymentView, HTMLIrPaymentViewElement>('ir-payment-view');
export const IrPhoneInput = /*@__PURE__*/createReactComponent<JSX.IrPhoneInput, HTMLIrPhoneInputElement>('ir-phone-input');
export const IrPickup = /*@__PURE__*/createReactComponent<JSX.IrPickup, HTMLIrPickupElement>('ir-pickup');
export const IrPopover = /*@__PURE__*/createReactComponent<JSX.IrPopover, HTMLIrPopoverElement>('ir-popover');
export const IrPrivacyPolicy = /*@__PURE__*/createReactComponent<JSX.IrPrivacyPolicy, HTMLIrPrivacyPolicyElement>('ir-privacy-policy');
export const IrPropertyGallery = /*@__PURE__*/createReactComponent<JSX.IrPropertyGallery, HTMLIrPropertyGalleryElement>('ir-property-gallery');
export const IrQuickAuth = /*@__PURE__*/createReactComponent<JSX.IrQuickAuth, HTMLIrQuickAuthElement>('ir-quick-auth');
export const IrRadio = /*@__PURE__*/createReactComponent<JSX.IrRadio, HTMLIrRadioElement>('ir-radio');
export const IrRateplan = /*@__PURE__*/createReactComponent<JSX.IrRateplan, HTMLIrRateplanElement>('ir-rateplan');
export const IrRoomTypeAmenities = /*@__PURE__*/createReactComponent<JSX.IrRoomTypeAmenities, HTMLIrRoomTypeAmenitiesElement>('ir-room-type-amenities');
export const IrRoomtype = /*@__PURE__*/createReactComponent<JSX.IrRoomtype, HTMLIrRoomtypeElement>('ir-roomtype');
export const IrSelect = /*@__PURE__*/createReactComponent<JSX.IrSelect, HTMLIrSelectElement>('ir-select');
export const IrSeoInjector = /*@__PURE__*/createReactComponent<JSX.IrSeoInjector, HTMLIrSeoInjectorElement>('ir-seo-injector');
export const IrSheet = /*@__PURE__*/createReactComponent<JSX.IrSheet, HTMLIrSheetElement>('ir-sheet');
export const IrSignin = /*@__PURE__*/createReactComponent<JSX.IrSignin, HTMLIrSigninElement>('ir-signin');
export const IrSignup = /*@__PURE__*/createReactComponent<JSX.IrSignup, HTMLIrSignupElement>('ir-signup');
export const IrSocialButton = /*@__PURE__*/createReactComponent<JSX.IrSocialButton, HTMLIrSocialButtonElement>('ir-social-button');
export const IrSwitch = /*@__PURE__*/createReactComponent<JSX.IrSwitch, HTMLIrSwitchElement>('ir-switch');
export const IrTextarea = /*@__PURE__*/createReactComponent<JSX.IrTextarea, HTMLIrTextareaElement>('ir-textarea');
export const IrTooltip = /*@__PURE__*/createReactComponent<JSX.IrTooltip, HTMLIrTooltipElement>('ir-tooltip');
export const IrUserForm = /*@__PURE__*/createReactComponent<JSX.IrUserForm, HTMLIrUserFormElement>('ir-user-form');
